<!-- breadcrumb -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="<?php base_url();?>">Home</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="#">Tracking</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>Add Packing Bizhub Form</span>
        </li>
    </ul>
</div>

<div class="space-4"></div>
<div class="row">
    <div class="col-md-12">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">Add Packing Bizhub Form</div>
            </div>

            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form method="post" action="" class="form-horizontal" id="form-packing">
                    <input type="hidden" name="<?php echo $this->security->get_csrf_token_name(); ?>" value="<?php echo $this->security->get_csrf_hash(); ?>">
                    <div class="form-body">

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_product_id">Product</label>
                            <div class="col-md-3">
                                <div class="input-group">
                                    <input type="hidden" name="product_id" id="packing_product_id" class="form-control">
                                    <input type="text" name="product_code" id="packing_product_code" readonly="" class="form-control required" placeholder="Choose Product">
                                    <span class="input-group-btn">
                                        <button class="btn btn-success" type="button" onclick="showLovProduct('packing_product_id','packing_product_code')">
                                            <span class="fa fa-search icon-on-right bigger-110"></span>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_bizhub_kg">Weight(Kg)</label>
                            <div class="col-md-3">
                                <input type="text" name="packing_bizhub_kg" id="packing_bizhub_kg" class="form-control required">
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_bizhub_date">Packing Date</label>
                            <div class="col-md-2">
                                <input type="text" name="packing_bizhub_date" id="packing_bizhub_date" class="form-control required">
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-md-3 control-label" for="packing_bizhub_batch_number">Serial Number</label>
                            <div class="col-md-3">
                                <input type="text" name="packing_bizhub_batch_number" readonly="" class="form-control" placeholder="Serial Generated By System">
                            </div>
                            <label class="col-md-2 control-label" for="packing_bizhub_serial">Batch Number</label>
                            <div class="col-md-3">
                                <input type="text" name="packing_bizhub_serial" readonly="" class="form-control" placeholder="Batch Generated By System">
                            </div>
                        </div>

                        <hr>
                        <div class="row">
                            <div class="col-md-offset-1 col-md-10">
                                <h3>Source Package</h3>

                                <div class="form-group">
                                    <label class="col-md-3 control-label">Source Material</label>
                                    <div class="col-md-3">
                                        <div class="input-group">
                                            <input type="hidden" name="source_sortir_detail_id" id="source_sortir_detail_id" class="form-control">
                                            <input type="hidden" name="source_product_id" id="source_product_id" class="form-control">
                                            <input type="text" name="source_product_code" id="source_product_code" readonly="" class="form-control" placeholder="Choose Source">
                                            <span class="input-group-btn">
                                                <button class="btn btn-success" type="button" onclick="showLovSortir('source_sortir_detail_id','source_product_code','product_weight_compare','source_product_id')">
                                                    <span class="fa fa-search icon-on-right bigger-110"></span>
                                                </button>
                                            </span>
                                        </div>
                                    </div>

                                    <div class="col-md-3">
                                        <input type="text" id="source_product_weight" name="source_product_weight" class="form-control" placeholder="Weight(Kg)">
                                        <input type="hidden" id="product_weight_compare">
                                    </div>
                                    <div class="col-md-1">
                                        <button class="btn btn-primary" type="button" id="btn-add-source"> <i class="fa fa-plus"></i>Add Source </button>
                                    </div>
                                </div>

                                <table class="table table-bordered table-striped" id="tbl-packing-detail">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Source Material</th>
                                            <th>Weight(Kg)</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                    </tbody>
                                </table>
                            </div>

                        </div>

                    </div>

                    <div class="form-actions">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <button type="submit" name="submit" class="btn btn-success"> <i class="fa fa-save"></i> Save Data </button>
                                <button type="button" name="back" id="btn-back" class="btn btn-danger"><i class="fa fa-arrow-left"></i>Back</button>
                            </div>
                        </div>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
</div>

<?php $this->load->view('lov/lov_product_packing.php'); ?>
<?php $this->load->view('lov/lov_sortir_bizhub_detail.php'); ?>

<script>
    function showLovProduct(id, code) {
        modal_lov_product_show(id,code);
    }

    function showLovSortir(id, code, qty_field, source_product_id) {
        if( $('#packing_product_id').val() == "") {
            swal("Information","Choose product first","info");
            return;
        }
        modal_lov_sortir_bizhub_detail_show(id, code, qty_field, $('#packing_product_id').val(), source_product_id);
    }
</script>


<script>
    function insertDataRow() {

        var jumlah_baris = document.getElementById('tbl-packing-detail').rows.length;

        var sortir_bizhub_det_id = document.getElementById('source_sortir_detail_id').value;
        var product_id = document.getElementById('source_product_id').value;
        var product_code = document.getElementById('source_product_code').value;
        var weight = document.getElementById('source_product_weight').value;

        var tr = document.getElementById('tbl-packing-detail').insertRow(jumlah_baris);
        var tdNo = tr.insertCell(0);
        var tdProduct = tr.insertCell(1);
        var tdWeight = tr.insertCell(2);
        var tdAction = tr.insertCell(3);

        tdNo.innerHTML = jumlah_baris;
        tdProduct.innerHTML = '<input type="hidden" name="sortir_bizhub_det_id[]" value="'+ sortir_bizhub_det_id +'"><input type="hidden" name="product_ids[]" value="'+ product_id +'">' + product_code;
        tdWeight.innerHTML = '<input type="hidden" name="weight[]" value="'+ weight +'">' + weight;
        tdAction.innerHTML = '<button type="button" onclick="deleteDataRow(this);"><i class="fa fa-trash"></i> Delete </button>';

        document.getElementById('source_sortir_detail_id').value = "";
        document.getElementById('source_product_id').value = "";
        document.getElementById('source_product_code').value = "";
        document.getElementById('source_product_weight').value = "";
        document.getElementById('product_weight_compare').value = "";
    }

    function deleteDataRow(sender) {
        $(sender).parent().parent().remove();
    }

</script>

<script>
    $(function() {
        $("#packing_bizhub_date").datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            orientation: 'bottom',
            todayHighlight: true
        });

        $("#btn-back").on('click', function(e) {
            loadContentWithParams('agripro.packing_bizhub',{});
        });

        $("#btn-add-source").on('click', function(e) {

            var product_id = $('#packing_product_id').val();
            var packing_bizhub_kg = $('#packing_bizhub_kg').val();
            var packing_bizhub_date = $('#packing_bizhub_date').val();

            if(product_id == "" || packing_bizhub_kg == "" || packing_bizhub_date == "") {
                swal('Information','Product, Weight, and Packing Date must be filled first','info');
                return;
            }

            var sortir_detail_id = $('#source_sortir_detail_id').val();
            var packing_weight = $('#source_product_weight').val();
            var packing_weight_compact = $('#product_weight_compare').val();

            if(sortir_detail_id == "" || packing_weight == "") {
                swal('Information','Source Material and Weight must be filled','info');
                return;
            }

            var packing_bizhub_kg_float = parseFloat(packing_bizhub_kg);
            var packing_weight_float = parseFloat(packing_weight);
            var packing_weight_compact_float = parseFloat(packing_weight_compact);

            if( packing_weight_float > packing_weight_compact_float ) {
                swal('Information','Weight greater than source weight','info');
                return;
            }

            if( packing_weight_float > packing_bizhub_kg_float ) {
                swal('Information','Weight greater than packing capacity weight','info');
                return;
            }

            var source_sortir_detail_ids = $('[name="sortir_bizhub_det_id[]"]');
            if(source_sortir_detail_ids.length > 0) {
                var error = false;
                $('[name="sortir_bizhub_det_id[]"]').each(function(index) {
                    if(sortir_detail_id == $(this).val()) {
                        swal('Information','Oops, we found double source package. choose another source','info');
                        error = true;
                    }
                });
                if(error) return;
            }

            insertDataRow();
        });


        $('#product_weight_compare').on('change', function(e){
            $('#source_product_weight').val(this.value);
        });

        $("#form-packing").submit(function(e) {
            e.preventDefault(); // avoid to execute the actual submit of the form.

            if($("#form-packing").valid() == true){
                var url = '<?php echo WS_JQGRID."agripro.packing_bizhub_controller/createForm"; ?>';
                $.ajax({
                    type: "POST",
                    url: url,
                    dataType : 'json',
                    data: $("#form-packing").serialize(),
                    success: function(response) {

                        if(response.success != true){
                            swal('Warning',response.message,'warning');
                        }else{
                            loadContentWithParams('agripro.packing_bizhub',{});
                        }

                    }
                });
            }

        });


    });
</script>